[project]
name = "hello"
version = "0.1.0"
description = "Hello CLI"
requires-python = ">=3.11"
dependencies = [
  "click>=8.1"
]

[project.scripts]
hello = "hello.hello:cli"
glow = "glow:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
